name: lint

on:
  merge_group:
  pull_request:

jobs:
  lint:
    name: lint:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main

      - name: Check TypeScript Formatting
        run: pnpm format:check

      - name: Check Rust Linting
        run: cargo clippy

      - name: Check Rust formatting
        run: cargo fmt -- --check
